### ISSUE TITLE
Feature Toggles not working in Rails

### ISSUE THREAD

**Issue by Nogah-Goldberg** [Unleash/unleash-client-ruby#28] opened 2019-10-30 12:10 UTC
Hi,
I am created a new feature flag and with a strategy to only work for users that have a specific property, but for some reason this isn't working for me. What am I doing wrong?

**I did the following:**

**1. I created a feature toggle called 'nogah_test'**
<img width="871" alt="Screen Shot 2019-10-30 at 14 04 22" src="https://user-images.githubusercontent.com/31074212/67856887-36e3cc00-fb1e-11e9-8877-b8e6f70ff552.png">

**2. I added a strategy called companyId which is a list of companyIds** 
<img width="907" alt="Screen Shot 2019-10-30 at 14 03 17" src="https://user-images.githubusercontent.com/31074212/67856902-3e0ada00-fb1e-11e9-8251-1a84f6355570.png">

**3. I added the strategy to my feature toggle with a specific companyId of 10 (my company Id)**
<img width="845" alt="Screen Shot 2019-10-30 at 14 06 22" src="https://user-images.githubusercontent.com/31074212/67857016-7ca09480-fb1e-11e9-91da-91f849f40f51.png">

**4. My code looks like this:**
This is my @unleash_context
<img width="371" alt="Screen Shot 2019-10-30 at 14 07 38" src="https://user-images.githubusercontent.com/31074212/67857156-bbcee580-fb1e-11e9-9b86-fe86ad3abda8.png">

when I do:
`Unleash::Client.new.is_enabled?('nogah_test', @unleash_context)`

it returns true, but when I just add a random companyId to the context or even change properties to be an empty hash, I still get true. It ignores the properties hash for some reason.
It only checks to see if the feature is enabled or disabled.

We know that a similar implementation works for Node.js, but here it doesn't. 
Could it be that it just doesn't work in Ruby?  

How come??? Thanks.

**Comment by rarruda** [comment] 2019-10-30 21:17
Hi,

I would need to look at the implementation of the custom strategy to be able to understand where the issue is. So if you can, please share the code for the custom strategy.

The client is quite verbose if you enable debug logging. So enabling that might give you quite a bit of insight into what's happening under the hood, and should help you troubleshoot issues with the custom strategy.

But I would think that the custom strategy should look something like this for it to work:
```ruby
module Unleash
  module Strategy
    class CompanyId < Base
      PARAM = 'companyId'.freeze

      def name
        'companyId'
      end

      # need: params['companyId'], context.properties['companyId']
      def is_enabled?(params = {}, context = nil)
        return false unless params.is_a?(Hash) && params.has_key?(PARAM)
        return false unless params.fetch(PARAM, nil).is_a? String
        return false unless context.class.name == 'Unleash::Context'

        params[PARAM].split(',').map(&:strip).include?(context.properties.fetch('companyId'))
      end
    end
  end
end
```
NOTE: not tested the code above!

And it must be in `lib/unleash/strategy` path. See https://github.com/Unleash/unleash-client-ruby/blob/v0.1.6/lib/unleash.rb#L8-L21 as to how the client scans for strategies.

I would also recommend packaging it as a separate Gem, with this client as a requisite.

I really should write a how-to write custom strategies for the ruby client, so I will put this in my TODO list. But it would also be useful to have an issue for tracking. :)

Let me know if these pointers have helped. If not, it would be important to see the code for your custom strategy.

**Comment by ahmetacer5** [comment] 2019-12-03 13:44
Hi @rarruda 

Can we load custom strategies from specific folder instead from lib/unleash/strategy?

**Comment by rarruda** [comment] 2019-12-04 09:03
Hi @ahmetacer5,

This is not currently supported, as what we do is to look up all the strategies loaded in the namespace via `Unleash::Strategy.constants`:

https://github.com/Unleash/unleash-client-ruby/blob/4c46deb9e969d277695dae775b1223f306746b80/lib/unleash.rb#L13-L21

I would recommend creating a supplementary gem which depends on this gem, and has the file in this path.

I see that the need for a guide on writing custom strategies is getting more pressing, so I will try to prioritize that.

**Comment by rarruda** [comment] 2020-02-06 22:56
Following up this in #30 . 

Link to the example on how to implement a custom strategy can be found in there.

Closing this issue. Thanks helping make the ruby client better! :)

**Closed by rarruda** 2020-02-06 22:56 UTC
